topdf:
	pandoc --template=default.latex --latex-engine=xelatex -V fontsize=13pt part1.md -o part1.pdf
	pandoc --template=default.latex --latex-engine=xelatex -V fontsize=13pt part2.md -o part2.pdf
	pandoc --template=default.latex --latex-engine=xelatex -V fontsize=13pt part3.md -o part3.pdf
